version-template: '$MAJOR.$MINOR.$PATCH.0'
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
exclude-labels:
  - 'skip-changelog'
  - 'automated-pull-request'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance'
    label: 'chore'
change-template: '* $TITLE (#$NUMBER) @$AUTHOR'
template: |
  Thanks to: $CONTRIBUTORS
  ## Changes
  $CHANGES