language: java
sudo: false
dist: xenial
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2
jdk:
- openjdk8
- openjdk11
install: true
script: ./travis/build.sh